using System.Text.Json;using System.Xml.Linq;using GmpCompanyCollector.App.Models;
namespace GmpCompanyCollector.App.Utilities;
public static class ApiErrorMapper{static readonly Dictionary<string,string> Map=new(){["1"]="공공데이터 서버에서 처리 오류가 발생했습니다. 잠시 후 다시 시도하십시오.",["10"]="요청 파라미터가 올바르지 않습니다. 검색조건을 확인하십시오.",["12"]="해당 OpenAPI가 존재하지 않거나 서비스가 종료되었습니다.",["20"]="API 접근이 거부되었습니다. 활용신청 승인 여부를 확인하십시오.",["22"]="일일 또는 시간당 API 요청 한도를 초과했습니다.",["30"]="등록되지 않은 인증키입니다. 인증키와 인코딩 형식을 확인하십시오.",["31"]="OpenAPI 활용기간이 만료되었습니다. 공공데이터포털에서 갱신하십시오.",["32"]="등록되지 않은 IP에서 요청했습니다. 운영계정 설정을 확인하십시오.",["99"]="공공데이터 서버에서 알 수 없는 오류가 발생했습니다."]; public static string ToKorean(string? code)=>code!=null&&Map.TryGetValue(code,out var m)?m:$"알 수 없는 오류 코드입니다. 코드: {code}";}
public static class ApiResponseParser{
 public static ApiResponse<CompanyListItem> ParseCompanyList(string raw)=>Parse(raw,MapCompany);
 public static ApiResponse<FactoryDetailItem> ParseFactoryDetails(string raw)=>Parse(raw,MapFactory);
 static ApiResponse<T> Parse<T>(string raw,Func<Dictionary<string,string>,T> map){raw=(raw??"").Trim(); if(raw.StartsWith('<'))return ParseXml(raw,map); if(raw.StartsWith('{')||raw.StartsWith('['))return ParseJson(raw,map); throw new InvalidDataException("응답 형식을 인식할 수 없습니다: "+raw[..Math.Min(80,raw.Length)]);}
 static ApiResponse<T> ParseXml<T>(string raw,Func<Dictionary<string,string>,T> map){var x=XDocument.Parse(raw); var err=x.Descendants("cmmMsgHeader").FirstOrDefault(); if(err!=null){var code=err.Element("returnReasonCode")?.Value??""; return new(new ApiHeader(code,ApiErrorMapper.ToKorean(code),err.Element("returnAuthMsg")?.Value,code),new(0,0,0,[]));} var h=x.Descendants("header").FirstOrDefault(); var b=x.Descendants("body").FirstOrDefault(); var items=x.Descendants("item").Select(e=>map(e.Elements().ToDictionary(a=>a.Name.LocalName,a=>TextCleaner.Clean(a.Value),StringComparer.OrdinalIgnoreCase))).ToList(); return new(new ApiHeader(h?.Element("resultCode")?.Value??"00",h?.Element("resultMsg")?.Value??""),new(Int(b,"pageNo"),Int(b,"numOfRows"),Int(b,"totalCount"),items));}
 static ApiResponse<T> ParseJson<T>(string raw,Func<Dictionary<string,string>,T> map){using var d=JsonDocument.Parse(raw); var root=d.RootElement; if(root.TryGetProperty("response",out var r))root=r; var h=root.TryGetProperty("header",out var hh)?hh:default; var b=root.TryGetProperty("body",out var bb)?bb:default; var list=new List<T>(); if(b.ValueKind!=JsonValueKind.Undefined&&b.TryGetProperty("items",out var items)){if(items.ValueKind==JsonValueKind.Object&&items.TryGetProperty("item",out var item))Add(item); else Add(items);} void Add(JsonElement e){if(e.ValueKind==JsonValueKind.Array){foreach(var v in e.EnumerateArray())Add(v);} else if(e.ValueKind==JsonValueKind.Object){list.Add(map(e.EnumerateObject().ToDictionary(p=>p.Name,p=>p.Value.ValueKind==JsonValueKind.Null?"":TextCleaner.Clean(p.Value.ToString()),StringComparer.OrdinalIgnoreCase)));}}
 return new(new ApiHeader(Prop(h,"resultCode","00"),Prop(h,"resultMsg","")),new(PropI(b,"pageNo"),PropI(b,"numOfRows"),PropI(b,"totalCount"),list));}
 static string Prop(JsonElement e,string n,string def)=>e.ValueKind!=JsonValueKind.Undefined&&e.TryGetProperty(n,out var v)?v.ToString()!:def; static int PropI(JsonElement e,string n)=>int.TryParse(Prop(e,n,"0"),out var i)?i:0; static int Int(XElement? e,string n)=>int.TryParse(e?.Element(n)?.Value,out var i)?i:0;
 static CompanyListItem MapCompany(Dictionary<string,string> d){string g(string k)=>d.TryGetValue(k,out var v)?TextCleaner.Clean(v):""; var (dt,ok)=DateParser.Parse(g("PRMISN_DT")); var (sido,sgg)=AddressParser.Parse(g("ADRES")); return new(){Induty=g("INDUTY"),Entrps=g("ENTRPS"),NormalizedEntrps=CompanyNameNormalizer.Normalize(g("ENTRPS")),Rprsntv=g("RPRSNTV"),PrmisnDt=g("PRMISN_DT"),PrmisnDateDisplay=dt,IsValidDate=ok,Adres=g("ADRES"),PrmisnNo=g("PRMISN_NO"),Sido=sido,Sigungu=sgg};}
 static FactoryDetailItem MapFactory(Dictionary<string,string> d){string g(string k)=>d.TryGetValue(k,out var v)?TextCleaner.Clean(v):""; var addr=AddressParser.Combine(g("FCTRY_ADDR1"),g("FCTRY_ADDR2")); var (dt,ok)=DateParser.Parse(g("PRMISN_DT")); var (sido,sgg)=AddressParser.Parse(addr); return new(){Entrps=g("ENTRPS"),NormalizedEntrps=CompanyNameNormalizer.Normalize(g("ENTRPS")),Induty=g("INDUTY"),PrmisnNo=g("PRMISN_NO"),Rprsntv=g("RPRSNTV"),PrmisnDt=g("PRMISN_DT"),PrmisnDateDisplay=dt,IsValidDate=ok,Sn=g("SN"),FctryNm=g("FCTRY_NM"),Telno=g("TELNO"),FctryAddr1=g("FCTRY_ADDR1"),FctryAddr2=g("FCTRY_ADDR2"),CombinedFactoryAddress=addr,Sido=sido,Sigungu=sgg};}
}
