namespace GmpCompanyCollector.App.Models;
public enum ServiceKeyMode{Auto,Decoding,Encoding} public enum CollectionKind{CompanyListOnly,FactoryDetailOnly,Both}
public record ApiHeader(string ResultCode="00",string ResultMsg="NORMAL SERVICE.",string? ReturnAuthMsg=null,string? ReturnReasonCode=null){public bool IsSuccess=>ResultCode is "00" or "0" && string.IsNullOrWhiteSpace(ReturnReasonCode);} 
public record ApiBody<T>(int PageNo,int NumOfRows,int TotalCount,List<T> Items);
public record ApiResponse<T>(ApiHeader Header,ApiBody<T> Body){public bool IsSuccess=>Header.IsSuccess;}
public class CompanyListItem{public bool IsSelected{get;set;} public string Induty{get;set;}=""; public string Entrps{get;set;}=""; public string NormalizedEntrps{get;set;}=""; public string Rprsntv{get;set;}=""; public string PrmisnDt{get;set;}=""; public string PrmisnDateDisplay{get;set;}=""; public bool IsValidDate{get;set;} public string Adres{get;set;}=""; public string PrmisnNo{get;set;}=""; public string Sido{get;set;}=""; public string Sigungu{get;set;}=""; public bool IsDuplicate{get;set;} public int DuplicateGroupNo{get;set;}}
public class FactoryDetailItem{public bool IsSelected{get;set;} public string Entrps{get;set;}=""; public string NormalizedEntrps{get;set;}=""; public string Induty{get;set;}=""; public string PrmisnNo{get;set;}=""; public string Rprsntv{get;set;}=""; public string PrmisnDt{get;set;}=""; public string PrmisnDateDisplay{get;set;}=""; public bool IsValidDate{get;set;} public string Sn{get;set;}=""; public string FctryNm{get;set;}=""; public string Telno{get;set;}=""; public string FctryAddr1{get;set;}=""; public string FctryAddr2{get;set;}=""; public string CombinedFactoryAddress{get;set;}=""; public string Sido{get;set;}=""; public string Sigungu{get;set;}=""; public bool IsDuplicate{get;set;} public int DuplicateGroupNo{get;set;}}
public class CollectionOptions{public CollectionKind Kind{get;set;}=CollectionKind.Both; public string ServiceKey{get;set;}=""; public ServiceKeyMode KeyMode{get;set;}=ServiceKeyMode.Auto; public string Induty{get;set;}=""; public string Entrps{get;set;}=""; public string PrmisnDt{get;set;}=""; public string PrmisnNo{get;set;}=""; public int NumOfRows{get;set;}=100; public string Type{get;set;}="json"; public int MaxSafePages{get;set;}=10000; public int RequestDelayMs{get;set;}=150;}
public class CollectionProgress{public string CurrentTask{get;set;}=""; public int CurrentPage{get;set;} public int TotalPages{get;set;} public int ReceivedCount{get;set;} public int TotalExpectedCount{get;set;} public int SuccessRequests{get;set;} public int FailedRequests{get;set;} public double Percent=>TotalExpectedCount<=0?0:Math.Min(100,ReceivedCount*100d/TotalExpectedCount); public TimeSpan Elapsed{get;set;}}
public record BasicStatistics(int CompanyRecordCount,int UniqueCompanyCount,int UniquePermitCount,int FactoryCount,int FactoryWithAddressCount,int FactoryWithPhoneCount,int MissingCompanyNameCount,int MissingPermitNoCount,int MissingAddressCount,int MissingRepresentativeCount,int InvalidDateCount,int DuplicateSuspectCount);
public record IndustryStatistics(string Induty,int UniqueCompanyCount,int PermitCount,int FactoryCount,double Ratio);
public record RegionStatistics(string Sido,int UniqueCompanyCount,int FactoryCount,double Ratio);
